version: 0.0
os: linux
files:
  - source: path/to/java-tomcat-maven-example.war
    destination: /opt/apache-tomcat/webapps/
hooks:
    BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

